wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1642690391
    t:
      1:
      - 1
      3:
      - 16
      4: 3.8.10
      5: 0.12.9
      8:
      - 5
name:
  desc: null
  value: kt_hidden_20
parameters:
  desc: null
  value:
    batch_size: 32
    decays: 0.9
    epochs: 30
    hidden_dims: 20
    learning_rate: 0.002
    optimizer: adam
